spring.application.name=uq-ai-backend

server.port=8080

spring.datasource.url=jdbc:h2:mem:BD_Tito_Arian_T1
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

jwt.secret=uqAiSolutionSecretKey2026ProgramacionSeguraDD281
jwt.expiration=86400000
cors.allowed.origins=http://localhost:3000